<?php

namespace FrontOfficeBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getArticlePres()
	{
		$query=$this->getEntitymanager()->createQuery('
			SELECT a 
			FROM FrontOfficeBundle:Article a 
			WHERE a.origin = 1');

		return $query->getResult();
	}

	public function getArticleMent()
	{
		$query=$this->getEntitymanager()->createQuery('
			SELECT a 
			FROM FrontOfficeBundle:Article a 
			WHERE a.origin = 2');

		return $query->getResult();
	}

	public function getArticleCondi()
	{
		$query=$this->getEntitymanager()->createQuery('
			SELECT a 
			FROM FrontOfficeBundle:Article a 
			WHERE a.origin = 3');

		return $query->getResult();
	}
}
