<?php

namespace FrontOfficeBundle\Repository;

/**
 * DateTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateTripRepository extends \Doctrine\ORM\EntityRepository
{
}
