<?php

namespace FrontOfficeBundle\Repository;

/**
 * EstimateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstimateRepository extends \Doctrine\ORM\EntityRepository
{
	public function getEstimatesNonTreated()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT e 
			FROM FrontOfficeBundle:Estimate e 
			WHERE e.state = 0
			AND e.archived = false
			ORDER BY e.dateSended ASC')
		->setMaxResults(5);

		return $query->getResult();
	}

	public function getEstimatesNonProcessedNonLimited()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT e 
			FROM FrontOfficeBundle:Estimate e 
			WHERE e.archived = false
			ORDER BY e.dateSended DESC');

		return $query->getResult();
	}

	public function countEstimatesNonProcessedNonLimited()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT COUNT(e.id) 
			FROM FrontOfficeBundle:Estimate e 
			WHERE e.state = 0
			AND e.archived = false');

		return $query->getSingleScalarResult();
	}

	public function countEstimatesProcessed()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT COUNT(e.id) 
			FROM FrontOfficeBundle:Estimate e 
			WHERE e.state = 1');

		return $query->getSingleScalarResult();
	}

	public function countEstimatesTreated()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT COUNT(e.id) 
			FROM FrontOfficeBundle:Estimate e 
			WHERE e.state = 2');

		return $query->getSingleScalarResult();
	}
}
