<?php

namespace FrontOfficeBundle\Repository;

/**
 * MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends \Doctrine\ORM\EntityRepository
{
	public function countAbo()
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT COUNT(m.id)
			FROM FrontOfficeBundle:Mail m');

		return $query->getSingleScalarResult();
	}
}
