<?php

namespace FrontOfficeBundle\Repository;

/**
 * ThematicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThematicRepository extends \Doctrine\ORM\EntityRepository
{
	public function getThematicActivated()
	{
		$query=$this->getEntitymanager()->createQuery('
			SELECT t 
			FROM FrontOfficeBundle:Thematic t 
			WHERE t.active = 1');

		return $query->getResult();
	}
}
