<?php

namespace FrontOfficeBundle\Repository;

/**
 * UnderlineTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnderlineTripRepository extends \Doctrine\ORM\EntityRepository
{
}
