<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function countUsers($role)
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT COUNT(u.id)
			FROM UserBundle:User u 
			WHERE u.roles != :role')
		->setParameter('role', $role);

		return $query->getSingleScalarResult();
	}
}
