services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    user.registration:
            class: UserBundle\Form\RegistrationFormType
            tags:
                - { name: form.type, firstname: form.type, adress: form.type, postcode: form.type, city: form.type, phoneNumber: form.type, alias: user_form_registration}
